import { Josefin_Sans } from "next/font/google";
import "./globals.css";
import Navber from "@/components/Navber";
import Footer from "@/components/Footer";

const josefin= Josefin_Sans({
  subsets: ["latin"],
});



export const metadata = {
  title: "Wanderlust",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${josefin.className}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <main>
          <Navber/>
          {children}
          <Footer/>
        </main>
        </body>
    </html>
  );
}
